from __future__ import annotations

import importlib.util
from pathlib import Path


def _load_normalize_svg():
    root = Path(__file__).resolve().parents[1]
    mod_path = root / "scripts" / "normalize_graphviz_svg.py"
    assert mod_path.exists(), f"missing: {mod_path}"

    spec = importlib.util.spec_from_file_location("_normalize_graphviz_svg", str(mod_path))
    assert spec and spec.loader, "failed to create module spec for normalize_graphviz_svg.py"

    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[attr-defined]
    assert hasattr(mod, "normalize_svg"), "normalize_svg() not found in normalize_graphviz_svg.py"
    return mod.normalize_svg


def test_normalize_strips_graphviz_generator_comment():
    normalize_svg = _load_normalize_svg()

    raw = """<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by graphviz version 9.0.0 (20240101.0000) -->
<svg xmlns="http://www.w3.org/2000/svg">
  <g></g>
</svg>
"""

    out = normalize_svg(raw)
    assert "Generated by graphviz version" not in out
    assert out.endswith("\n")


def test_normalize_collapses_excess_blank_lines():
    normalize_svg = _load_normalize_svg()

    raw = "<svg>\n\n\n\n<g></g>\n</svg>"
    out = normalize_svg(raw)
    assert "\n\n\n" not in out
    assert out.endswith("\n")
