#!/usr/bin/env python3
import re
import sys
from pathlib import Path


def normalize_svg(text: str) -> str:
    # Graphviz often includes a generator comment that varies by version/build:
    # <!-- Generated by graphviz version X.Y.Z (...) -->
    text = re.sub(r"(?m)^\s*<!--\s*Generated by graphviz.*?-->\s*\n?", "", text)

    # Sometimes there are extra blank lines introduced/removed across versions.
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Canonical newline at EOF
    if not text.endswith("\n"):
        text += "\n"
    return text


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: normalize_graphviz_svg.py <file.svg>", file=sys.stderr)
        return 2
    fp = Path(sys.argv[1])
    raw = fp.read_text(encoding="utf-8")
    norm = normalize_svg(raw)
    if norm != raw:
        fp.write_text(norm, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
