import importlib.util
from pathlib import Path

# Path-based import to avoid pytest `tests/scripts/` shadowing the top-level `scripts/` package
_spec = importlib.util.spec_from_file_location(
    "normalize_graphviz_svg",
    Path(__file__).resolve().parents[3] / "scripts" / "orbit" / "normalize_graphviz_svg.py",
)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
normalize_svg = _mod.normalize_svg


def test_normalize_strips_graphviz_generator_comment():
    raw = """<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by graphviz version 9.0.0 (20240101.0000) -->
<svg xmlns="http://www.w3.org/2000/svg">
  <g></g>
</svg>
"""
    out = normalize_svg(raw)
    assert "Generated by graphviz version" not in out
    assert out.endswith("\n")


def test_normalize_collapses_excess_blank_lines():
    raw = "<svg>\n\n\n\n<g></g>\n</svg>"
    out = normalize_svg(raw)
    assert "\n\n\n" not in out
    assert out.endswith("\n")
