#!/usr/bin/env python3
"""
Generate mu/docs/README.md index automatically.

Scans docs/ subdirectories and creates a navigable index.
Run manually or as part of pre-commit to keep index fresh.

Usage:
    python tools/generate_docs_index.py
    python tools/generate_docs_index.py --check  # Verify index is up-to-date
"""

import argparse
import re
import sys
from pathlib import Path

# Directory descriptions (customize as needed)
DIR_DESCRIPTIONS = {
    "core": "Core specifications - read these first",
    "execution": "Execution semantics and traces",
    "schemas": "JSON schema definitions",
    "cli": "CLI tools and commands",
    "agents": "AI agent rig documentation",
    "audit": "Audit, governance, and compliance",
    "fixtures": "Test fixtures",
    "reviews": "Design reviews and summaries",
    "roadmap": "Roadmap specs and gate plans",
}

# Priority order for directories (higher = listed first)
DIR_PRIORITY = {
    "core": 100,
    "execution": 90,
    "schemas": 70,
    "cli": 60,
    "agents": 50,
    "audit": 40,
    "roadmap": 30,
    "reviews": 20,
    "fixtures": 5,
}

DOC_HEADER_TEMPLATE = """<!--
DOC_STATUS
TYPE: REFERENCE
LAST_VERIFIED: 2026-01-01
OWNER: RCX Core Team
FOR_CURRENT_STATE: See STATUS.md and TASKS.md
GROUNDING_TESTS: tests/docs/test_doc_contracts.py

This header enables automated doc drift detection.
- REFERENCE: Stable definitions, rarely changes
- DESIGN_SPEC: Architectural intent, may diverge from implementation
- IMPLEMENTATION: Active development, should match current code

If this doc's claims don't match reality, update the doc or fix the code.
Run: pytest tests/docs/test_doc_contracts.py -v
-->"""


def extract_existing_header(readme_path: Path) -> str:
    """Extract existing DOC_STATUS block from mu/docs/README.md, if present."""
    if not readme_path.exists():
        return DOC_HEADER_TEMPLATE
    content = readme_path.read_text(encoding="utf-8")
    # Match the full <!-- DOC_STATUS ... --> block (search handles BOM/leading whitespace)
    m = re.search(r"(<!--\s*\nDOC_STATUS\b.*?-->)", content, re.DOTALL)
    if m:
        return m.group(1)
    return DOC_HEADER_TEMPLATE


def extract_title(filepath: Path) -> str:
    """Extract title from markdown file (first # heading or filename)."""
    try:
        content = filepath.read_text(encoding="utf-8")
        # Look for first # heading
        match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
        if match:
            return match.group(1).strip()
    except Exception:
        pass
    # Fallback to filename without extension
    return filepath.stem.replace("_", " ").replace("-", " ")


def generate_index(docs_dir: Path) -> str:
    """Generate the README.md content."""
    readme_path = docs_dir / "README.md"
    header = extract_existing_header(readme_path)
    lines = [
        header,
        "",
        "# Documentation Index",
        "",
        "> Auto-generated by `tools/generate_docs_index.py`",
        "> Run `python tools/generate_docs_index.py` to update",
        "",
        "## Quick Links",
        "",
        "| Category | Description |",
        "|----------|-------------|",
    ]

    # Collect directories
    dirs = []
    for d in docs_dir.iterdir():
        if d.is_dir() and not d.name.startswith("."):
            dirs.append(d)

    # Sort by priority then name
    dirs.sort(key=lambda d: (-DIR_PRIORITY.get(d.name, 0), d.name))

    # Add quick links table
    for d in dirs:
        desc = DIR_DESCRIPTIONS.get(d.name, "")
        lines.append(f"| [{d.name}/](#{d.name}) | {desc} |")

    lines.append("")

    # Add detailed sections for each directory
    for d in dirs:
        lines.append(f"## {d.name}")
        lines.append("")

        desc = DIR_DESCRIPTIONS.get(d.name, "")
        if desc:
            lines.append(f"*{desc}*")
            lines.append("")

        # Find all markdown files
        md_files = sorted(d.glob("*.md"))
        if md_files:
            lines.append("| File | Title |")
            lines.append("|------|-------|")
            for f in md_files:
                title = extract_title(f)
                rel_path = f.relative_to(docs_dir)
                lines.append(f"| [{f.name}]({rel_path}) | {title} |")
            lines.append("")
        else:
            # Check for other files
            other_files = [f for f in d.iterdir() if f.is_file() and not f.name.startswith(".")]
            if other_files:
                lines.append(f"*{len(other_files)} files (non-markdown)*")
                lines.append("")
            else:
                subdirs = [sd for sd in d.iterdir() if sd.is_dir()]
                if subdirs:
                    lines.append(f"*Contains subdirectories: {', '.join(sd.name for sd in subdirs)}*")
                    lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*To add a new doc: create the file, then run `python tools/generate_docs_index.py`*")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate mu/docs/README.md index")
    parser.add_argument("--check", action="store_true", help="Check if index is up-to-date")
    args = parser.parse_args()

    # Find docs directory
    script_dir = Path(__file__).parent
    docs_dir = script_dir.parent / "mu" / "docs"

    if not docs_dir.exists():
        print(f"Error: docs directory not found at {docs_dir}")
        sys.exit(1)

    readme_path = docs_dir / "README.md"
    new_content = generate_index(docs_dir)

    if args.check:
        # Check mode - verify index is up-to-date
        if readme_path.exists():
            current_content = readme_path.read_text(encoding="utf-8")
            if current_content.strip() == new_content.strip():
                print("mu/docs/README.md is up-to-date")
                sys.exit(0)
            else:
                print("mu/docs/README.md is OUT OF DATE")
                print("Run: python tools/generate_docs_index.py")
                sys.exit(1)
        else:
            print("mu/docs/README.md does not exist")
            print("Run: python tools/generate_docs_index.py")
            sys.exit(1)
    else:
        # Generate mode
        readme_path.write_text(new_content, encoding="utf-8")
        print(f"Generated {readme_path}")

        # Count what was indexed
        md_count = len(list(docs_dir.rglob("*.md")))
        dir_count = len([d for d in docs_dir.iterdir() if d.is_dir()])
        print(f"  {dir_count} directories, {md_count} markdown files indexed")


if __name__ == "__main__":
    main()
